# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: terraform-backend-kv
- name: TF_VAR_key
  value: $(Build.Repository.Name).tfstate

stages:
  - stage: docker
    jobs:
    - job: docker_stuff
      steps:
      - task: DownloadSecureFile@1
        name: application_properties
        displayName: 'Download application.properties'
        inputs:
          secureFile: 'quackers-bank-application.properties'
      - script: |
           pwd
           ls -lta
           ls src/main
           sudo ln -s -t $(System.DefaultWorkingDirectory)/src/main/resources/ $(application_properties.secureFilePath)
           ls src/main/resources
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: acrquackbank
      - task: Docker@2
        displayName: Build and Push
        inputs:
          command: buildAndPush
          repository: quackersbank
          tags: |
            latest
  - stage: terraform
    jobs:
    - job: do_terraform
      steps:
      - task: FuncToolsInstaller@0
        displayName: "Install Function Tool"
      - script: terraform --version
        displayName: 'check terraform version'
      - task: AzureCLI@2
        displayName: "Terraform Init"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            cd terraform
            echo "starting..."
            echo $TF_VAR_key
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            ./env_setup.sh
            echo $TF_VAR_container_name
            terraform init --backend-config=backend.tfvars
        env:
          TF_VAR_subscription_id: $(subscription-id)
          TF_VAR_storage_account_name: $(storage-account-name)
          TF_VAR_resource_group_name: $(resource-group-name)
          TF_VAR_key: $(TF_VAR_key)
          TF_VAR_container_name: $(container-name)
      - task: AzureCLI@2
        displayName: "Terraform Plan"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            cd terraform
            echo "starting..."
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            terraform plan -out theplan
        env:
          TF_VAR_subscription_id: $(subscription-id)
          TF_VAR_storage_account_name: $(storage-account-name)
          TF_VAR_resource_group_name: $(resource-group-name)
          TF_VAR_key: $(TF_VAR_key)
          TF_VAR_container_name: $(container-name)
      - task: AzureCLI@2
        displayName: "Terraform Apply"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            cd terraform
            echo "starting..."
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            terraform apply -auto-approve theplan
        env:
          TF_VAR_subscription_id: $(subscription-id)
          TF_VAR_storage_account_name: $(storage-account-name)
          TF_VAR_resource_group_name: $(resource-group-name)
          TF_VAR_key: $(TF_VAR_key)
          TF_VAR_container_name: $(container-name)