apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sql
  namespace: quackersbank
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: quackersbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      serviceAccountName: uai-kvcsidriver-quackbanky2pis47k
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: 'mcr.microsoft.com/mssql/server:2019-latest'
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wisecret
              key: DB-PASSWORD 
        volumeMounts:
        - name: mssql
          mountPath: /var/opt/mssql
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: mssql
        persistentVolumeClaim:
          claimName: pvc-sql
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-sync-workload-identity"
          #nodePublishSecretRef:
          #  name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: quackersbank
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 31433
      targetPort: 1433
  type: LoadBalancer