apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-api
  namespace: quackersbank
  labels:
    app: transactions-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-api
  template:
    metadata:
      labels:
        app: transactions-api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: uai-kvcsidriver-quackbankl6ht6vt8
      containers:
      - name: transactions-api
        image: ghcr.io/implodingduck/quackers-bank-transactions-api:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: APPLICATIONINSIGHTS_CONFIGURATION_FILE
          value: "/opt/target/config/applicationinsights.json"
        - name: ACCOUNTSAPI_BASEURL
          value: http://accounts-api
        - name: TRANSACTIONSAPI_BASEURL
          value: http://transactions-api
        - name: ACCOUNTS_SCOPES
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: accountsscopes
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: appinsightsconnectionstring
        - name: B2C_BASE_URI
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: b2cbaseuri
        - name: B2C_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: b2cclientidtransactions
        - name: B2C_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: b2cclientsecrettransactions
        - name: B2C_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: b2ctenantid
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: dbpassword
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: dburl
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: dbusername
        - name: TRANSACTIONS_SCOPES
          valueFrom:
            secretKeyRef:
              name: workidsyncsecret
              key: transactionsscopes
        volumeMounts:
        - name: app-props
          mountPath: "/opt/target/config"
          readOnly: true
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: app-props
        secret:
          secretName: transactions-application-properties
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-sync-workload-identity"
---
apiVersion: v1
kind: Service
metadata:
  name: transactions-api
  namespace: quackersbank
  labels:
    app: transactions-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: transactions-api